### ISSUE TITLE
关于sqlite的包的选择

### ISSUE THREAD

**Issue by eryajf** [shenghui0779/yiigo#15]
目前选用的是 github.com/mattn/go-sqlite3，这个需要依赖CGO，如果使用的话，其实对系统环境侵入还是比较大的。

github也有纯go实现的sqlite库，比如：https://github.com/glebarez/sqlite  ，建议也可以考虑选择这个库。

**Comment by shenghui0779** [comment]
这个库与go-sqlite3比，除了不依赖CGO，还有其它什么优势？

**Comment by eryajf** [comment]
> 这个库与go-sqlite3比，除了不依赖CGO，还有其它什么优势？

没有做更多的对比

**Comment by shenghui0779** [comment]
我看目前主流的库还是：go-sqlite3，暂时不动，至于你说的这个库，后面观察，看其他流行库的支持程度，如：ent 等

**Comment by eryajf** [comment]
ok
