### ISSUE TITLE
请问这个log日志输出顺序是随机的吗?

### ISSUE THREAD

**Issue by a411500412** [shenghui0779/yiigo#4]
![image](https://user-images.githubusercontent.com/35193629/91317951-42ab2800-e7ed-11ea-9dae-fc4717340b54.png)

例如上面一段代码 , 为什么会先输出1234 , 再输出123和126126呢?

**Comment by shenghui0779** [comment]
![image](https://user-images.githubusercontent.com/67535398/91583337-a7988680-e983-11ea-9f04-842904655241.png)

你这个情况我确实没遇到过 😅

**Comment by a411500412** [comment]
我是用goland直接右键run的 , 并且并不是每次都这样 . 如果用命令go run main.go好像确实不会出现这种情况
