### ISSUE TITLE
使用ToBatchInsert方法，入参是[]*struct，会发生异常

### ISSUE THREAD

**Issue by daniel-007** [shenghui0779/yiigo#7]
panic: reflect: call of reflect.Value.NumField on zero Value
github.com/shenghui0779/yiigo.(*QueryWrapper).batchInsertWithStruct(0xc000161400, 0x1b1f680, 0xc000a16000, 0x97)
.../mod/github.com/shenghui0779/yiigo@v1.0.6/sql_builder.go:299 +0x111

**Comment by shenghui0779** [comment]
test是OK的，你的 []*struct 数据是啥？我看能不能复现

**Comment by shenghui0779** [comment]
不提供，我关了哈
